version: '3'

services:
  webapi:
    image: webapi
    build:
      context: ./Timer.WebApi
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  postgres:
    image: postgres
    ports:
      - "6432:5432"
    # volumes:
     # - /c/Temp/postgres/var/lib/postgresql:/var/lib/postgresql